name: Publish Package to GitHub Packages
on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Run tests
    uses: ctrl-hub/infra.github-actions/.github/workflows/ci-kotlin-test.yaml@v8

  build:
    name: Build and Publish Artifact
    runs-on: ubuntu-latest
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code with Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Kotlin
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: 21
          cache: gradle
      - name: Build and Publish Artifact
        run: ./gradlew clean publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}